---
- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Intstall packages.
  apt:
    name: "{{item}}"
    state: latest
 # when: ansible_os_family == 'Debian'
  with_items:
    - python-apt
    - aptitude
    - git
    - autoconf 
    - libtool 
    - pkg-config 
    - gcc 
    - g++
    - libssl-dev 
    - libpam0g-dev 
    - libjpeg-dev 
    - libx11-dev 
    - libxfixes-dev 
    - libxrandr-dev  
    - flex 
    - bison 
    - libxml2-dev 
    - intltool 
    - xsltproc 
    - xutils-dev 
    - python-libxml2  
    - xutils 
    - libfuse-dev 
    - libmp3lame-dev 
    - nasm 
    - libpixman-1-dev 
    - xserver-xorg-dev 
    - libopus-dev
    - make


